version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ""
        LoadBalancerInfo:
          ContainerName: "prod-yeohaeng-api"
          ContainerPort: 8080
        PlatformVersion: "LATEST"